# OFFSET event-triggered distributed estimation simulation config

max_time: 20
dt: 0.1

monte_carlo_sims: True
num_mc_sims: 5

delta_values: [1.0]
tau_values: [5]
msg_drop_prob_values: [0.0]

use_adaptive_tau: True
fixed_rng: False

# data compression techniques
quantization: True
diagonalization: True

agent_cfg:
    conn_struct_type: "tree"
    # conns: [[9],[9],[10],[10],[11],[11],[12],[12],
    #         [1,2,13],[3,4,13],[5,6,14],[7,8,14],[9,10,15],[11,12,15],[13,14,16],
    #         [15,17,18],[16,19,20],[16,21,22],[17,23,24],[17,25,26],[18,27,28],
    #         [18,29,30],[19],[19],[20],[20],[21],[21],[22],[22]]
    # conns: [[8],[8],[9],[9],[10],[10],[11],[11],
    #        [0,1,12],[2,3,12],[4,5,13],[6,7,13],[8,9,14],[10,11,14],[12,13,15],
    #        [14,16,17],[15,18,19],[15,20,21],[16,22,23],[16,24,25],[17,26,27],
    #        [17,28,29],[18],[18],[19],[19],[20],[20],[21],[21]]
    conns: [[2],[2],[0,1,3],[2,4,5],[3],[3]]
    dynamics_fxn: "lin_ncv_3d"
    sensors:
        lin_abs_pos:
            agents: [0,5]
            # agents: [13,14,17,18]
            noise: [[1,0,0],[0,1,0],[0,0,1]]
        lin_rel_range:
            agents: "all"
            noise: [[3,0,0],[0,3,0],[0,0,3]]

baseline_cfg:
    dynamics_fxn: "lin_ncv_3d"
    sensors:
        lin_abs_pos:
            agents: [0,5]
            # agents: [13,14,17,18]
            noise: [[1,0,0],[0,1,0],[0,0,1]]
        lin_rel_range:
            agents: "all"
            noise: [[3,0,0],[0,3,0],[0,0,3]]
