update_rate: 10


# FOR HARDWARE
# Change depth topic, add_depth_bias

## Multipliers for Delta tiers
## increases a measurements threshold to be added to the buffer by the given amount
delta_tiers: [1]

## Measurement topics
measurement_topics:
  depth: "mavros/global_position/rel_alt" # "baro"
  imu_ci: "None"
  imu_est: "odometry/filtered" #"pose_gt" # "mavros/global_position/local"
  sonar: "sonar_processing/target_list/associated"
  add_depth_bias: False # Add depth bias in hardware to keep the agent from bottominng out

### Buffer space configurations ###
buffer_space:
  capacity: 28 # Total capacity, should be 28
  bookstart: 1 # Space for indicating START of measurement stream
  bookend: 1 # Space for indicating STOP of meas stream
  final_time: 0 # Space to send last time in buffer

use_control_input: False

### Initial Mean Estimate Configurations ###
default_starting_position:
  x: 0.0
  y: 0.0
  z: 0.0
  x_vel: 0.0
  y_vel: 0.0
  z_vel: 0.0

### Process Noise Configurations ###
process_noise:
  ownship:
    x: 0.001
    y: 0.001
    z: 0.001
    x_vel: 0.001
    y_vel: 0.001
    z_vel: 0.001
  blueteam:
    x: 0.001
    y: 0.001
    z: 0.001
    x_vel: 0.001
    y_vel: 0.001
    z_vel: 0.001
  redteam:
    x: 0.001
    y: 0.001
    z: 0.001
    x_vel: 0.001
    y_vel: 0.001
    z_vel: 0.001

### Initial Uncertainty Configurations ###
initial_uncertainty:
  ownship:
    x: 1.0
    y: 1.0
    z: 1.0
    x_vel: 0.01
    y_vel: 0.01
    z_vel: 0.01
  # for asset positions provided to us through roslaunch params
  known_starting_position: 
    x: 1.0
    y: 1.0
    z: 1.0
    x_vel: 0.01
    y_vel: 0.01
    z_vel: 0.01
  # asset positions not provided in roslaunch, including redteam
  unknown_starting_position: 
    x: 1000
    y: 1000
    z: 8
    x_vel: 1.0
    y_vel: 1.0
    z_vel: 1.0