update_rate: 10

## Multipliers for Delta tiers
## increases a measurements threshold to be added to the buffer by the given amount
delta_tiers: [1]

## Measurement topics
measurement_topics:
  depth: "mavros/global_position/rel_alt"
  imu_ci: "None"
  imu_est: "odometry/filtered" #"pose_gt" # "mavros/global_position/local"
  sonar: "sonar_processing/target_list/associated"

  # TODO verify mavros_global_position/rel_alt

### Buffer space configurations ###
buffer_space:
  capacity: 32 # Total capacity
  bookstart: 1 # Space for indicating START of measurement stream
  bookend: 1 # Space for indicating STOP of meas stream
  final_time: 0 # Space to send last time in buffer

use_control_input: False

### Initial Mean Estimate Configurations ###
default_starting_position:
  x: 0.0
  y: 0.0
  z: 0.0
  x_vel: 0.0
  y_vel: 0.0
  z_vel: 0.0

### Process Noise Configurations ###
process_noise:
  ownship:
    x: 0.0001
    y: 0.0001
    z: 0.01
    x_vel: 0.0001
    y_vel: 0.0001
    z_vel: 0.1
  blueteam:
    x: 0.0
    y: 0.0
    z: 0.0
    x_vel: 0.0
    y_vel: 0.0
    z_vel: 0.0
  redteam:
    x: 0.1
    y: 0.1
    z: 0.1
    x_vel: 0.05
    y_vel: 0.05
    z_vel: 0.05

### Initial Uncertainty Configurations ###
initial_uncertainty:
  ownship:
    x: 1.0
    y: 1.0
    z: 1.0
    x_vel: 0.2
    y_vel: 0.2
    z_vel: 0.2
  # for asset positions provided to us through roslaunch params
  known_starting_position: 
    x: 0.0
    y: 0.0
    z: 0.0
    x_vel: 0.0
    y_vel: 0.0
    z_vel: 0.0
  # asset positions not provided in roslaunch, including redteam
  unknown_starting_position: 
    x: 1000
    y: 1000
    z: 8
    x_vel: 1.0
    y_vel: 1.0
    z_vel: 1.0